apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30869
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 32236 # Make ArgoCD accessible via 10.33.0.3:32236
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
