apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: animal-facts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/animal-facts/gitops.git
    targetRevision: HEAD
    path: .
  destination:
    namespace: animal-api
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
