apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: braum-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dj-braum/gitops-dev.git
    targetRevision: HEAD
    path: overlays/dev
  destination:
    namespace: braum-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: braum-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dj-braum/gitops-prod.git
    targetRevision: HEAD
    path: manifests
  destination:
    namespace: braum-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
